### PR TITLE
Migrate to Android Studio Bumblebee

### PR DESCRIPTION
**Pull request by BD103**
This PR covers everything that should come with the migration to Android Studio Bumblebee (from Arctic Fox).

- [ ] Apply any fixes necessary for migration
- [x] Bump Gradle and Gradle plugin versions

A side note, Bumblebee introduces a [new device manager](https://developer.android.com/studio/releases#new-device-manager) and [wireless debugging](https://developer.android.com/studio/releases#wireless-debugging). Hopefully there is a way to use these tools to their fullest capabilities. 

## Some more notes

- Bumblebee also upgrades the base IntelliJ IDE platform to 2021.1.1.
  - Because of this, the Lombok plugin is merged into the IDE's main codebase. If you have the Lombok plugin, you can uninstall it.
- I may update this PR with more notices as I find them.
- This PR is going to remain a draft for a few days while I test out Bumblebee. After that, it should be safe to merge.

### CODE REVIEW

**Comment by BD103** [comment]
Also Travis is failing because JCenter is returning a 403 error. It isn't just Travis, I cannot access https://jcenter.bintray.com from both my phone and laptop. `./gradlew build` works properly on my device, though. (Probably because the Jars are cached?)

Another note, I have tested this PR by building it and running it on the robot, so it does work with minimal testing.

**Comment by BD103** [comment]
It seems that Lombok isn't completely integrated, as it isn't detecting the created getter and setter methods. This gives an code linting error, but building is still fine.

**Review by 9p4 — COMMENTED** [review]
Looks good so far. I'll have to pull this and try to iron our the rest of the issues. Good work!

**Review by 9p4 — APPROVED** [review]
LGTM

**Pull request merged**
